services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=stationskidb
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - custom_network

  app-station:
    depends_on:
      - mysqldb
    image: rihemoueslati/imagefinal
    restart: on-failure
    ports:
      - 8081:8081
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://localhost:3306/stageete2024?&createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
        "spring.datasource.username": "root",
        "spring.datasource.password": "",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    stdin_open: true
    tty: true
    networks:
      - custom_network

volumes:
  db:

networks:
  custom_network:
    driver: bridge
